# api_response.settings:
#   type: config_object
#   label: 'Custom API Security Settings'
#   mapping:
#     api_secret_key:
#       type: string
#       label: 'API Secret Key'
#       description: 'The secret key to access the API.'
#       default_value: ''
